mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
spring:
#垂直拆分 的表的普通 mybatis 配置 无需配置表名
  normal:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.160:3306/goods_db?characterEncoding=utf-8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
#有2个 dataSource 接口的 实现 解决报错问题
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    sharding:
#     配置关联表 用于关联查询
#      binding-tables[0]: goods,user
#      binding-tables[1]: test1,test2
#       可配置广播表： 每个库共享的表
#      broadcast-tables: t_config
      tables:
#       user表用于测试 分库分表后关联数据, user只分库 未分表
        user:
          actual-data-nodes: g$->{1..2}.user
          key-generator:
            column: gid
            type: SNOWFLAKE
          database-strategy:
            inline:
              sharding-column: id
              algorithm-expression: g$->{id % 2 + 1}
#        t_config:
#          actual-data-nodes: ds$->{0}.t_config
        #必须配置 表名  下面全是goods表的全部配置信息
        goods:
          #分库分表策略
          actual-data-nodes: g$->{1..2}.goods_$->{1..2}
          #主键生成算法  可用雪花算法SnowflakeShardingKeyGenerator 或者 UUID UUIDShardingKeyGenerator，或者自己实现接口 自定义
          key-generator:
            column: gid
            type: SNOWFLAKE
          #分表策略  对2 取模，列名  和  策略
          table-strategy:
            inline:
              sharding-column: gid
              algorithm-expression: goods_$->{gid % 2 + 1}
#              precise-algorithm-class-name 可自己定义分片策略
          #分库策略 对2 取模，列名 和  策略
          database-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: g$->{user_id % 2 + 1}
    #数据库配置
    datasource:
      names: g1,g2
      g1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.10.160:3306/goods_db_1?characterEncoding=utf-8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: root
        password: root
      g2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.10.160:3306/goods_db_2?characterEncoding=utf-8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: root
        password: root
    #sql log显示
    props:
      sql:
        show: true
